"""Initial_migration

Revision ID: 795afb11af4b
Revises: 
Create Date: 2026-03-09 14:43:23.735602

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '795afb11af4b'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_ui_translations_english_key', table_name='ui_translations')
    op.drop_index('ix_ui_translations_id', table_name='ui_translations')
    op.drop_table('ui_translations')
    op.add_column('patients', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'patients', 'users', ['user_id'], ['id'], ondelete='SET NULL')
    op.add_column('users', sa.Column('hashed_password', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'hashed_password')
    op.drop_constraint(None, 'patients', type_='foreignkey')
    op.drop_column('patients', 'user_id')
    op.create_table('ui_translations',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('english_key', sa.VARCHAR(length=512), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('en', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('hi', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('ta', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('te', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('bn', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('mr', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('kn', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('ml', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('gu', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('pa', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('or', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('as', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('ur', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('fr', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('de', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('es', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('zh', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('ja', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('ko', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('ar', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('ru', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('pt', sa.TEXT(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='ui_translations_pkey')
    )
    op.create_index('ix_ui_translations_id', 'ui_translations', ['id'], unique=False)
    op.create_index('ix_ui_translations_english_key', 'ui_translations', ['english_key'], unique=True)
    # ### end Alembic commands ###
